<a href="https://colab.research.google.com/github/tontantip/DADS5001-In-Class/blob/main/plotly_go.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import plotly.express as px

##วิเคราะห์ GDP
df = px.data.gapminder()
df.head()
df = px.data.gapminder().query("country=='Thailand'")
fig = px.line(df, x="year", y="lifeExp", title='Life expectancy in Thailand')
fig.show()

In [26]:
import plotly.express as px

df = px.data.gapminder().query("continent=='Asia'")
print(df.head())
fig = px.line(df, x="year", y="lifeExp", color='country', symbol='country')
fig.show()

       country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0  Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1  Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2  Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3  Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4  Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   

   iso_num  
0        4  
1        4  
2        4  
3        4  
4        4  


In [27]:
import plotly.express as px

df = px.data.stocks()
print(df.head())
print(df.shape)
fig = px.line(df, x='date', y="AAPL")
fig.show()

         date      GOOG      AAPL      AMZN        FB      NFLX      MSFT
0  2018-01-01  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
1  2018-01-08  1.018172  1.011943  1.061881  0.959968  1.053526  1.015988
2  2018-01-15  1.032008  1.019771  1.053240  0.970243  1.049860  1.020524
3  2018-01-22  1.066783  0.980057  1.140676  1.016858  1.307681  1.066561
4  2018-01-29  1.008773  0.917143  1.163374  1.018357  1.273537  1.040708
(105, 7)


In [37]:
import plotly.express as px
df = px.data.stocks(indexed=True)
fig = px.bar(df, facet_row="company", facet_row_spacing=0.01, height=300, width=400)

# hide and lock down axes
## ใช้ function update
fig.update_xaxes(visible=False, fixedrange=True)
fig.update_yaxes(visible=False, fixedrange=True)

# remove facet/subplot labels
fig.update_layout(annotations=[], overwrite=True)

# strip down the rest of the plot
## สร้างกราบของ grahp
fig.update_layout(
    showlegend=False,
    plot_bgcolor="light blue",
    margin=dict(t=10,l=10,b=10,r=10)
)

# disable the modebar for such a small plot
fig.show(config=dict(displayModeBar=False))

In [35]:
df.columns

Index(['GOOG', 'AAPL', 'AMZN', 'FB', 'NFLX', 'MSFT'], dtype='object', name='company')

In [46]:
import plotly.graph_objects as go
#df = px.data.stocks(indexed=True)
## Create random data with numpy
#import numpy as np
#np.random.seed(1)

##N = 100
#random_x = np.linspace(0, 1, N)
#random_y0 = np.random.randn(N) + 5
#random_y1 = np.random.randn(N)
#random_y2 = np.random.randn(N) - 5
import plotly.express as px

# 1. โหลดข้อมูลหุ้นมาตรฐาน
df = px.data.stocks(indexed=True)
#
# Create traces
fig = go.Figure()
fig.add_trace(go.Scatter(x=df.date, y=df.GOOG,
                    mode='lines',
                    name='Google'))
fig.add_trace(go.Scatter(x=df.date, y=df.AAPL,
                    mode='lines+markers',
                    name='Apple'))
fig.add_trace(go.Scatter(x=df.date, y=df.AMZN,
                    mode='markers', name='Amazon'))

fig.show()

AttributeError: 'DataFrame' object has no attribute 'date'

In [59]:
import plotly.graph_objects as go
import plotly.express as px

# 1. โหลดข้อมูลหุ้นมาตรฐาน
df = px.data.stocks(indexed=True) # Date is in the index

# Create traces
fig = go.Figure()

# เพิ่ม Trace GOOG (ใช้ df.index สำหรับแกน X)
fig.add_trace(go.Scatter(x=df.index, y=df['GOOG'],
                         mode='lines', # เส้น
                         name='Google'))

# เพิ่ม Trace AAPL (ใช้ df.index สำหรับแกน X)
fig.add_trace(go.Scatter(x=df.index, y=df['AAPL'],
                         mode='lines+markers', # เส้นและจุด
                         name='Apple'))

# เพิ่ม Trace AMZN (ใช้ df.index สำหรับแกน X)
fig.add_trace(go.Scatter(x=df.index, y=df['AMZN'],
                         mode='markers', # จุด
                         name='Amazon'))
#
#fig.add_trace(go.Scatter(x=df.index, y=df['NFLX'],
#                         mode='markers', # จุด
#                         name='Netfilx',
#                        dash='dash'))
#

fig.add_trace(go.Scatter(
    x=df.index,
    y=df['NFLX'],
    mode='lines', # เปลี่ยนเป็น 'lines' หรือ 'lines+markers'
    name='Netflix',
    line=dict(
        dash='dash',      # <<< ต้องกำหนด dash ภายใน line=dict(...)
        color='red',      # (ทางเลือก) กำหนดสี
        width=2           # (ทางเลือก) กำหนดความหนา
    )
))

# ปรับปรุง Layout
fig.update_layout(
    title='Stock Prices Over Time (GOOG, AAPL, AMZN)',
    xaxis_title='Date',
    yaxis_title='Stock Price',
    ## แสดงราคาเทียบของแต่ละตัว
    hovermode='x unified',
    ## แสดง ราคาปิดของแต่ละจุด
    #hovermode='closest'
)

# บันทึกเป็น JSON
#fig.write_json("stock_time_series_plot.json")
fig.show()

In [60]:
import plotly.graph_objects as go
import numpy as np

title = 'Main Source for News'
labels = ['Television', 'Newspaper', 'Internet', 'Radio']
colors = ['rgb(67,67,67)', 'rgb(115,115,115)', 'rgb(49,130,189)', 'rgb(189,189,189)']

mode_size = [8, 8, 12, 8]
line_size = [2, 2, 4, 2]

x_data = np.vstack((np.arange(2001, 2014),)*4)
print(x_data)

y_data = np.array([
    [74, 82, 80, 74, 73, 72, 74, 70, 70, 66, 66, 69],
    [45, 42, 50, 46, 36, 36, 34, 35, 32, 31, 31, 28],
    [13, 14, 20, 24, 20, 24, 24, 40, 35, 41, 43, 50],
    [18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23],
])

fig = go.Figure()

for i in range(0, 4):
    fig.add_trace(go.Scatter(x=x_data[i], y=y_data[i], mode='lines',
        name=labels[i],
        line=dict(color=colors[i], width=line_size[i]),
        connectgaps=True,
    ))

    # endpoints
    fig.add_trace(go.Scatter(
        x=[x_data[i][0], x_data[i][-1]],
        y=[y_data[i][0], y_data[i][-1]],
        mode='markers',
        marker=dict(color=colors[i], size=mode_size[i])
    ))
    print([x_data[i][0], x_data[i][-1]])

fig.update_layout(
    xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linecolor='rgb(204, 204, 204)',
        linewidth=2,
        ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
            color='rgb(82, 82, 82)',
        ),
    ),
    yaxis=dict(
        showgrid=False,
        zeroline=False,
        showline=False,
        showticklabels=False,
    ),
    autosize=False,
    margin=dict(
        autoexpand=False,
        l=100,
        r=20,
        t=110,
    ),
    showlegend=False,
    plot_bgcolor='white'
)

annotations = []

# Adding labels
for y_trace, label, color in zip(y_data, labels, colors):
    # labeling the left_side of the plot
    annotations.append(dict(xref='paper', x=0.05, y=y_trace[0],
                                  xanchor='right', yanchor='middle',
                                  text=label + ' {}%'.format(y_trace[0]),
                                  font=dict(family='Arial',
                                            size=16),
                                  showarrow=False))
    # labeling the right_side of the plot
    annotations.append(dict(xref='paper', x=0.95, y=y_trace[11],
                                  xanchor='left', yanchor='middle',
                                  text='{}%'.format(y_trace[11]),
                                  font=dict(family='Arial',
                                            size=16),
                                  showarrow=False))
# Title
annotations.append(dict(xref='paper', yref='paper', x=0.0, y=1.05,
                              xanchor='left', yanchor='bottom',
                              text='Main Source for News',
                              font=dict(family='Arial',
                                        size=30,
                                        color='rgb(37,37,37)'),
                              showarrow=False))
# Source
annotations.append(dict(xref='paper', yref='paper', x=0.5, y=-0.1,
                              xanchor='center', yanchor='top',
                              text='Source: PewResearch Center & ' +
                                   'Storytelling with data',
                              font=dict(family='Arial',
                                        size=12,
                                        color='rgb(150,150,150)'),
                              showarrow=False))

fig.update_layout(annotations=annotations)

fig.show()

[[2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013]
 [2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013]
 [2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013]
 [2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013]]
[np.int64(2001), np.int64(2013)]
[np.int64(2001), np.int64(2013)]
[np.int64(2001), np.int64(2013)]
[np.int64(2001), np.int64(2013)]


## Mixed subplot

In [64]:
## ใช้ go
import plotly.graph_objects as go
## ใช้ make subplot
from plotly.subplots import make_subplots

import pandas as pd

# read in volcano database data ออกสามารถ set มาจาก volcano db
df = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/volcano_db.csv",
    encoding="iso-8859-1",
)

# frequency of Country
freq = df['Country'].value_counts().reset_index()
freq.columns = ['x', 'Country']

# read in 3d volcano surface data
df_v = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/volcano.csv")

# Initialize figure with subplots
fig = make_subplots(
    rows=2, cols=2,
    column_widths=[0.6, 0.4],
    row_heights=[0.4, 0.6],
    specs=[[{"type": "scattergeo", "rowspan": 2}, {"type": "bar"}],
           [            None                    , {"type": "surface"}]])

# Add scattergeo globe map of volcano locations
fig.add_trace(
    go.Scattergeo(lat=df["Latitude"],
                  lon=df["Longitude"],
                  mode="markers",
                  hoverinfo="text",
                  showlegend=False,
                  marker=dict(color="crimson", size=4, opacity=0.8)),
    row=1, col=1
)

# Add locations bar chart
fig.add_trace(
    go.Bar(x=freq["x"][0:10],y=freq["Country"][0:10], marker=dict(color="crimson"), showlegend=False),
    row=1, col=2
)

# Add 3d surface of volcano
fig.add_trace(
    go.Surface(z=df_v.values.tolist(), showscale=False),
    row=2, col=2
)

# Update geo subplot properties
fig.update_geos(
    projection_type="orthographic",
    landcolor="white",
    oceancolor="MidnightBlue",
    showocean=True,
    lakecolor="LightBlue"
)

# Rotate x-axis labels
fig.update_xaxes(tickangle=45)

# Set theme, margin, and annotation in layout
fig.update_layout(
    template="plotly_dark",
    margin=dict(r=10, t=25, b=40, l=60),
    annotations=[
        dict(
            text="Source: NOAA",
            showarrow=False,
            xref="paper",
            yref="paper",
            x=0,
            y=0)
    ]
)
# Update geo subplot properties
fig.update_geos(
    projection_type="orthographic",
    # *** เพิ่มบรรทัดนี้เพื่อกำหนดมุมเริ่มต้นของการหมุน ***
    projection_rotation=dict(lon=45, lat=0, roll=0),
    # ************************************************
    landcolor="white",
    oceancolor="MidnightBlue",
    showocean=True,
    lakecolor="LightBlue"
)

fig.show()

In [68]:
## ใช้ go
import plotly.graph_objects as go
## ใช้ make subplot
from plotly.subplots import make_subplots

import pandas as pd

# read in volcano database data ออกสามารถ set มาจาก volcano db
df = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/volcano_db.csv",
    encoding="iso-8859-1",
)

# frequency of Country
freq = df['Country'].value_counts().reset_index()
freq.columns = ['x', 'Country']

# read in 3d volcano surface data

new_url = "https://raw.githubusercontent.com/plotly/datasets/master/api_docs/mt_bruno_elevation.csv"

#df_v = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/volcano.csv")
df_v = pd.read_csv(new_url)



# Initialize figure with subplots
fig = make_subplots(
    rows=2, cols=2,
    column_widths=[0.6, 0.4],
    row_heights=[0.4, 0.6],
    specs=[[{"type": "scattergeo", "rowspan": 2}, {"type": "bar"}],
           [            None                    , {"type": "surface"}]])

# Add scattergeo globe map of volcano locations
fig.add_trace(
    go.Scattergeo(lat=df["Latitude"],
                  lon=df["Longitude"],
                  mode="markers",
                  hoverinfo="text",
                  showlegend=False,
                  marker=dict(color="crimson", size=4, opacity=0.8)),
    row=1, col=1
)

# Add locations bar chart
fig.add_trace(
    go.Bar(x=freq["x"][0:10],y=freq["Country"][0:10], marker=dict(color="crimson"), showlegend=False),
    row=1, col=2
)

# Add 3d surface of volcano
fig.add_trace(
    go.Surface(z=df_v.values.tolist(), showscale=False),
    row=2, col=2
)


# Update geo subplot properties
fig.update_geos(
    projection_type="orthographic",
    landcolor="white",
    oceancolor="MidnightBlue",
    showocean=True,
    lakecolor="LightBlue"
)

# Rotate x-axis labels
fig.update_xaxes(tickangle=45)

# Set theme, margin, and annotation in layout
fig.update_layout(
    template="plotly_dark",
    margin=dict(r=10, t=25, b=40, l=60),
    annotations=[
        dict(
            text="Source: NOAA",
            showarrow=False,
            xref="paper",
            yref="paper",
            x=0,
            y=0)
    ]
)
# Update geo subplot properties
fig.update_geos(
    projection_type="orthographic",
    # *** เพิ่มบรรทัดนี้เพื่อกำหนดมุมเริ่มต้นของการหมุน ***
    #projection_rotation=dict(lon=60, lat=0, roll=0),
    ## หมุนให้เห็นประเทศญี่ปุ่น
    projection_rotation=dict(lon=138, lat=36, roll=0) ,
    # ************************************************
    landcolor="white",
    oceancolor="MidnightBlue",
    showocean=True,
    lakecolor="LightBlue"
)

fig.show()

## Animation
https://plotly.com/python/animations/

In [69]:
import plotly.express as px
df = px.data.gapminder()
px.scatter(df, x="gdpPercap", y="lifeExp", animation_frame="year", animation_group="country",
           size="pop", color="continent", hover_name="country",
           log_x=True, size_max=55, range_x=[100,100000], range_y=[25,90])

In [82]:
import plotly.express as px

# 1. โหลดข้อมูลหุ้น (เป็น Wide-form)
#    - คอลัมน์ date เป็นวันที่
#    - คอลัมน์อื่น ๆ เป็นราคาหุ้น (AAPL, GOOG, AMZN, MSFT, FB)
df = px.data.stocks()
# df.shape คือ (530, 6) ซึ่งครอบคลุมระยะเวลาประมาณ 5 ปี
print("Stocks Data Head:")
print(df.head())

# 2. แปลงข้อมูลจาก Wide-form เป็น Long-form
#    - เพื่อให้ Plotly สามารถใช้คอลัมน์ 'Company' แยกสีได้
df_long = df.melt(id_vars='date', var_name='Company', value_name='Price')

# 3. สร้างกราฟเส้นแอนิเมชัน
fig = px.line(
    df_long,
    x="date",
    y="Price",
    color="Company",
    # ใช้ animation_frame เป็น 'date' เพื่อให้กราฟวาดเพิ่มขึ้นทีละวัน
    animation_frame="date",
    animation_group="Price",
    # กำหนดให้เส้นทั้งหมดแสดงอยู่ตลอดเวลาเมื่อเฟรมเปลี่ยน
    # (แทนที่จะหายไปเมื่อเฟรมเปลี่ยนเหมือน Scatter plot)
    range_x=[df['date'].min(), df['date'].max()],
    title="Animated Stock Price Growth (5 Years)"
)

# ปรับ Layout ให้ดีขึ้น
fig.update_layout(
    xaxis_title="Date",
    yaxis_title="Stock Price"
)

# แสดงกราฟแอนิเมชัน
fig.show()

Stocks Data Head:
         date      GOOG      AAPL      AMZN        FB      NFLX      MSFT
0  2018-01-01  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
1  2018-01-08  1.018172  1.011943  1.061881  0.959968  1.053526  1.015988
2  2018-01-15  1.032008  1.019771  1.053240  0.970243  1.049860  1.020524
3  2018-01-22  1.066783  0.980057  1.140676  1.016858  1.307681  1.066561
4  2018-01-29  1.008773  0.917143  1.163374  1.018357  1.273537  1.040708


In [79]:
import plotly.express as px
import pandas as pd

# 1. โหลดข้อมูลหุ้น (เป็น Wide-form)
df = px.data.stocks()

# 2. แปลงข้อมูลจาก Wide-form เป็น Long-form
#    - ID: 'date'
#    - ตัวแปร (Company) ถูกรวมเป็นคอลัมน์ใหม่ชื่อ 'Company'
#    - ค่า (Price) ถูกรวมเป็นคอลัมน์ใหม่ชื่อ 'Price'
df_long = df.melt(id_vars='date', var_name='Company', value_name='Price')
print("Long-form Data Head:")
print(df_long.head())

# 3. สร้างกราฟเส้นแอนิเมชัน
fig = px.line(
    df_long,
    x="date",
    y="Price",
    color="Company",
    # กำหนดให้ 'date' เป็นแกนการเคลื่อนไหว (Animation Frame)
    animation_frame="date",
    range_x=[df['date'].min(), df['date'].max()],
    title="Animated Stock Price Growth (5 Years)"
)

# ปรับ Layout
fig.update_layout(
    xaxis_title="Date",
    yaxis_title="Stock Price"
)

# 4. บันทึกเป็น JSON แทน fig.show() เพื่อยืนยันผลลัพธ์
#fig.write_json("stock_animation_line_chart.json")

Long-form Data Head:
         date Company     Price
0  2018-01-01    GOOG  1.000000
1  2018-01-08    GOOG  1.018172
2  2018-01-15    GOOG  1.032008
3  2018-01-22    GOOG  1.066783
4  2018-01-29    GOOG  1.008773
